openapi: 3.0.3
info:
  description: API para consultar precios aplicables a productos en base a fecha,
    producto y marca
  title: Price API
  version: 1.0.0
servers:
- url: /
paths:
  /prices:
    get:
      operationId: getPrice
      parameters:
      - example: 2020-06-14T10:00:00
        explode: true
        in: query
        name: consultationDate
        required: true
        schema:
          format: date-time
          type: string
        style: form
      - example: 35455
        explode: true
        in: query
        name: productId
        required: true
        schema:
          type: integer
        style: form
      - example: 1
        explode: true
        in: query
        name: brandId
        required: true
        schema:
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PriceResponseDto'
          description: Precio encontrado
        "404":
          description: Precio no encontrado
        "400":
          description: Error en los parámetros de entrada
      summary: Obtener el precio aplicable
      x-accepts: application/json
components:
  schemas:
    PriceResponseDto:
      type: PriceResponseDto
      description: Clase Java existente
      additionalProperties: false